title: Shengdong (Shen) Zhao
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

markdown: kramdown

###############################################################
## SCSS settings.
###############################################################
sass:
  sass_dir: _scss
  style: compressed

collections:
  # category:
  #   output: true
  publications:
    output: true
    permalink: /:title/

paginate: 5
paginate_path: blogs/page:num/

# Prose.io setting

prose:
  rooturl: ''
  # siteurl: 'http://prose.github.io/starter/'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: '/assets/'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /publication
    - /team
    - /_scss
    - /pages
    - /js
    - .github
    - /blogs
    - .gitignore
    - 404.html
    - Gemfile
    - README.md

  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: ""
      - name: "image"
        field:
          label: "image"
          element: "text"
          value: "/assets/blog/placeholder-image.jpeg"
      - name: "description"
        field:
          label: 'description'
          element: "text"
          value: ""
      - name: "date"
        field:
          label: date
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "category"
        field:
          label: "category"
          element: "text"
          value: ""
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: ""
      - name: "pdf-link"
        field:
          label: "pdf-link"
          element: "text"
          value:
      - name: "page-link"
        field:
          label: "page-link"
          element: "text"
          value: ""
      - name: "video-link"
        field:
          label: "video-link"
          element: "text"
          value:
    _publications:
      - name: "title"
        field:
          label: "title"
          element: "text"
          value: ""
      - name: "image"
        field:
          label: "image"
          element: "text"
          value: "/assets/blog/placeholder-image.jpeg"
      - name: "description"
        field:
          label: 'description'
          element: "text"
          value: ""
      - name: "date"
        field:
          label: date
          element: "text"
          value: "CURRENT_DATETIME"
      - name: "category"
        field:
          label: "category"
          element: "text"
          value: ""
      - name: "author"
        field:
          label: "author"
          element: "text"
          value: ""
      - name: "pdf-link"
        field:
          label: "pdf-link"
          element: "text"
          value: 
      - name: "page-link"
        field:
          label: "page-link"
          element: "text"
          value: ""
      - name: "video-link"
        field:
          label: "video-link"
          element: "text"
          value: 


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
